18-auth/house-of-rails/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :statements, only: [:new, :create, :index, :edit, :update, :destroy, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # index
  # get '/politicians', to: 'politicians#index'
  # show
  # get '/politicians/:id', to: 'politicians#show'
  # new
  # get '/politicians/new', to: 'politicians#new'
  # create
  # post '/politicians', to: 'politicians#create'
  # edit
  # get '/politicians/:id/edit, to 'politicians#edit'
  # update
  # patch '/politicians/:id', to: 'politicians#update'
  # destroy
  # delete '/politicians/:id', to: 'politicians#destroy'

  # resources :politicians, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :politicians
  patch '/sessions/reset', to: 'sessions#reset_view_tracker'
  get '/signup', to: 'users#new', as: "signup"
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

18-auth/house-of-rails/app/models/statement.rb
class Statement < ApplicationRecord
  belongs_to :politician
  belongs_to :user

  # Task 1: statement declaration should be unique for a politician
  validates :declaration, uniqueness: {
    scope: :politician_id,
    message: "already saved this declaration for this politician"
  }

  # Task 2: statement year must be a number
  validates :year, numericality: { 
    only_integer: true,
    message: "must be integer" 
  }

  # Task 3: write a custom validation - the year must be after the year 1975
  validate :year_must_be_post_seventy_five


  def year_must_be_post_seventy_five
    # byebug
    if self.year < 1975
      errors.add(:year, "must be after 1975")
    end
  end
end

18-auth/house-of-rails/app/controllers/statements_controller.rb
class StatementsController < ApplicationController
    before_action :set_statement, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user, only: [:edit, :update, :destroy]
    
    def new
        if session[:user_id]
            @statement = Statement.new
            render :new
        else
            redirect_to login_path
        end
    end

    def create 
        merged_params = statement_params.merge(user_id: @current_user.id)
        statement = Statement.create(merged_params)
        redirect_to "/politicians/#{statement.politician.id}"
    end
    
    def show
        render :show
    end

    def index
        @statements = Statement.all
    end

    def edit
        if @current_user == @statement.user
            render :edit
        else
            redirect_to @statement
        end
    end

    def update
        @statement.update(statement_params)
        redirect_to statements_path
    end

    def destroy
        @statement.destroy
        redirect_to statements_path
    end

    private 

    def statement_params
        params.require(:statement).permit(:declaration, :truth, :year, :politician_id)
    end

    def authorize_user
        @statement = Statement.find(params[:id])
        redirect_to @statement unless @current_user == @statement.user
    end

    def set_statement
        @statement = Statement.find(params[:id])
    end
end

18-auth/house-of-rails/app/helpers/statements_helper.rb
module StatementsHelper
end

18-auth/house-of-rails/app/views/statements/edit.erb
<h1>Edit a statement!</h1>

<%= form_with model: @statement, html: { class: "form" } do |f| %>
    <%= f.label :declaration %>
    <%= f.text_field :declaration %>
    <br>
    <%= f.label :year %>
    <%= f.number_field :year %>
    <br>
    <%= f.label :politician_id %>
    <%= collection_select(:statement, :politician_id, Politician.all, :id, :name) %>
    <br>
    <%= f.label :truth %>
    <%= f.check_box :truth, :class => "checkbox" %>
    <br>
    <br>
    <%= f.submit "Edit Statement" %>
<% end %>

18-auth/house-of-rails/app/views/statements/index.erb
<h1>All the statements:</h1>
<ul>
<% @statements.each do |statement|%>
    <li><%= link_to statement.declaration, "/statements/#{statement.id}" %> | <%= statement.year %></li>
    <br>
<% end %>
</ul>
<br>
<hr>
☞ <%= link_to "Create a statement", new_statement_path %>

18-auth/house-of-rails/app/views/statements/new.erb
<h1>Create a new statement!</h1>

<%= form_with model: @statement, html: { class: "form" } do |f| %>
    <%= f.label :declaration %>
    <%= f.text_field :declaration %>
    <br>
    <%= f.label :year %>
    <%= f.number_field :year %>
    <br>
    <%= f.label :politician_id %>
    <%= collection_select(:statement, :politician_id, Politician.all, :id, :name) %>
    <br>
    <%= f.label :truth %>
    <%= f.check_box :truth, :class => "checkbox" %>
    <br>
    <br>
    <%= f.submit "Create Statement" %>
<% end %>

18-auth/house-of-rails/app/views/statements/show.erb
<h1><%= @statement.declaration %></h1>

<h4>Stated by <%= @statement.politician.name %> in the year <%= @statement.year %></h4>

<% if @current_user == @statement.user %>
    <%= button_to "Edit", edit_statement_path(@statement), method: :get %>
    <br>
    <%= button_to "Delete statement", @statement, method: :delete %>
<% end %>