18-auth/house-of-rails/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :statements, only: [:new, :create, :index, :edit, :update, :destroy, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # index
  # get '/politicians', to: 'politicians#index'
  # show
  # get '/politicians/:id', to: 'politicians#show'
  # new
  # get '/politicians/new', to: 'politicians#new'
  # create
  # post '/politicians', to: 'politicians#create'
  # edit
  # get '/politicians/:id/edit, to 'politicians#edit'
  # update
  # patch '/politicians/:id', to: 'politicians#update'
  # destroy
  # delete '/politicians/:id', to: 'politicians#destroy'

  # resources :politicians, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :politicians
  patch '/sessions/reset', to: 'sessions#reset_view_tracker'
  get '/signup', to: 'users#new', as: "signup"
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
end

18-auth/house-of-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseOfRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="body">
    <header class="menu">
        <div class="container">
          <nav>
            <%= link_to "Politicians", politicians_path, class: "item" %>
            <%= link_to "Create Politician", new_politician_path, class: "item" %>
          </nav>
          <nav class="right">
            <span class="item">
              <% if @current_user %>
                Welcome, <%= @current_user.username %>!
                <%= link_to "Logout", "/logout", method: :delete %>
              <% else %>
                <%= link_to "Sign Up", "/signup" %>
                <%= link_to "Log in", "/login" %>
              <% end %>
            </span>
          </nav>
        </div>
      </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>