18-auth/snacks_on_a_plane/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/snacks', to: 'snacks#index', as: 'snacks'
  get '/snacks/new', to: 'snacks#new', as: 'new_snack'
  get '/snacks/:id', to: 'snacks#show', as: 'snack'
  get '/snacks/:id/edit', to: 'snacks#edit', as: 'edit_snack'

  post '/snacks', to: 'snacks#create'
  patch '/snacks/:id', to: 'snacks#update'
  delete '/snacks/:id', to: 'snacks#destroy'

  # does all the work of ☝🏽 in one line
  resources :users
  resources :user_snacks

  delete 'reset_views', to: 'sessions#reset_views', as: 'reset'
  get '/signup', to: 'users#new', as: "signup"
  get '/login', to: 'sessions#new', as: "login"
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

## path helper
# snacks_path --> '/snacks'
# snack_path --> '/snacks/:id' (/snacks/8)
# new_snack_path --> '/snacks/new'
# edit_snack_path --> '/snacks/:id/edit' (/snacks/8/edit)

18-auth/snacks_on_a_plane/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

18-auth/snacks_on_a_plane/app/models/snack.rb
class Snack < ApplicationRecord
    has_many :user_snacks, dependent: :destroy
    has_many :users, through: :user_snacks
end

18-auth/snacks_on_a_plane/app/models/user.rb
class User < ApplicationRecord
    has_many :user_snacks
    has_many :snacks, through: :user_snacks
    has_secure_password

    validates :name, presence: true, uniqueness: true

    # def password=(plaintext_password)
    #     # run the plaintext password through a hashing algo
    #     encrypted_pw = BCrypt::Password.create(plaintext_password)
    #     # save the encrypted password to the database
    #     self.password_digest = encrypted_pw
    # end

    # def authenticate(plaintext_password)
    #     # pull out the password_digest string out of the database
    #     # and turn it into an instance Bcrypt::Password
    #     encrypted_pw = BCrypt::Password.new(self.password_digest)

    #     # compare the encrypted password to the plaintext_password
    #     encrypted_pw == plaintext_password
    # end
end

18-auth/snacks_on_a_plane/app/models/user_snack.rb
class UserSnack < ApplicationRecord
  belongs_to :user
  belongs_to :snack

  # review needs to be more than 10 characters
  validates :review, length: { minimum: 10 }

  # rating must be greater than 0 and less than 11
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 10 }

  # user can only review a snack once
  validates :user_id, uniqueness: { scope: :snack_id }
end

18-auth/snacks_on_a_plane/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    before_action :authorized

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def authorized
        redirect_to login_path unless @current_user
    end

end

18-auth/snacks_on_a_plane/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def reset_views
    # session[:page_views] = nil
    session.delete(:view_count)
    
    redirect_back fallback_location: users_path
  end 

  def new
  end

  def create
    # find the user in the database by the name
    user = User.find_by(name: params[:session][:name])
    # compare their password to whatever password was passed in the form
    if user.authenticate(params[:session][:password])
    # if the password is correct, save the user_id to the session
        session[:user_id] = user.id 
        redirect_to snacks_path
    else
        flash[:errors] = user.errors.full_messages
        redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end


end

18-auth/snacks_on_a_plane/app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
    before_action :find_snack, only: [:show, :edit, :update, :destroy]
    
    def index
        @snacks = Snack.all

        # render :index
    end

    def show
        # @snack = Snack.find(params[:id])

        # render :show
    end

    def new
        @snack = Snack.new

        # render :new
    end

    def create
        snack = Snack.create(snack_params)

        redirect_to snack_path(snack.id)
    end

    def edit
        # @snack = Snack.find(params[:id])
    end

    def update
        # @snack = Snack.find(params[:id])
        @snack.update(snack_params)

        redirect_to snack_path(@snack.id)
    end

    def destroy
        # @snack = Snack.find(params[:id])
        @snack.destroy

        redirect_to snacks_path
    end

    private

    def snack_params
        params.require(:snack).permit(:name, :brand, :flavor_profile)
    end

    def find_snack
        @snack = Snack.find(params[:id])
    end

end

18-auth/snacks_on_a_plane/app/controllers/user_snacks_controller.rb
class UserSnacksController < ApplicationController
    before_action :authorize_user, only: [:edit, :update, :destroy]
    before_action :find_user_snack, only: [:show, :edit, :update, :destroy]

    def new
        # if session[:user_id]
            @user_snack = UserSnack.new

            @users = User.all
            @snacks = Snack.all
            
        #     render :new
        # else
        #     redirect_to login_path
        # end
    end

    def create
        merged_params = user_snack_params.merge(user_id: @current_user.id)
        @user_snack = UserSnack.create(merged_params)

        if @user_snack.valid?
            redirect_to user_path(@user_snack.user.id) 
        else
            flash[:errors] = @user_snack.errors.full_messages

            redirect_to new_user_snack_path
        end   
    end

    def index
        @user_snacks = UserSnack.all
    end

    def show
        @user_snack = UserSnack.find(params[:id])
    end

    def edit
        @user_snack = UserSnack.find(params[:id])

        # if @current_user == @user_snack.user
            @snacks = Snack.all
            # render :edit
        # else
        #     redirect_to @user_snack
        # end
    end

    def update
        @user_snack.update(user_snack_params)
        redirect_to user_snacks_path
    end

    def destroy
        @user_snack.destroy
        redirect_to user_snacks_path
    end

    private

    def user_snack_params
        params.require(:user_snack).permit(:review, :rating, :user_id, :snack_id)
    end

    def authorize_user
        @user_snack = UserSnack.find(params[:id])
        redirect_to @user_snack unless @current_user == @user_snack.user
    end

    def find_user_snack
        @user_snack = UserSnack.find(params[:id])
    end
end

18-auth/snacks_on_a_plane/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        
        if session[:view_count] 
            session[:view_count] = session[:view_count].to_i + 1
        else 
            session[:view_count] = 1
        end 

        render :show
    end

    def new
        @user = User.new
    end
  
    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            redirect_to snacks_path
        else
            flash[:errors] = user.errors.full_messages
            redirect_to signup_path
        end 
    end

    private
    def user_params
        params.require(:user).permit(:name, :password, :motto, :img_url)
    end

end

18-auth/snacks_on_a_plane/app/helpers/application_helper.rb
module ApplicationHelper
end

18-auth/snacks_on_a_plane/app/helpers/sessions_helper.rb
module SessionsHelper
end

18-auth/snacks_on_a_plane/app/helpers/snacks_helper.rb
module SnacksHelper
end

18-auth/snacks_on_a_plane/app/helpers/user_snacks_helper.rb
module UserSnacksHelper
end

18-auth/snacks_on_a_plane/app/helpers/users_helper.rb
module UsersHelper
end

18-auth/snacks_on_a_plane/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnacksOnAPlane</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Snacks', snacks_path %>
      <%= link_to 'Users', users_path %>
      <%= link_to 'Create Snack', new_snack_path %>
      <%= link_to 'Review Snack', new_user_snack_path %>
    </nav>

    <% if @current_user %>
      <p> Welcome, <%= @current_user.name %> </p>
      <%= button_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", "/signup" %>
      <%= link_to "Log In", "/login" %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

18-auth/snacks_on_a_plane/app/views/snacks/_form.html.erb
<%= form_for @snack do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :brand %>
    <%= f.text_field :brand %>

    <%= f.label :flavor_profile %>
    <%= f.text_field :flavor_profile %>

    <%= f.submit %>
<% end %>

18-auth/snacks_on_a_plane/app/views/snacks/edit.html.erb
<h1>edit a snack</h1>

<%= render "form" %>

18-auth/snacks_on_a_plane/app/views/snacks/index.html.erb
<h1>snacks index page</h1>

<% @snacks.each do |snack| %>
    <p><%= link_to snack.name, snack_path(snack.id) %> </p>
<% end %>   

18-auth/snacks_on_a_plane/app/views/snacks/new.html.erb
<h1>create a snack</h1>

<%= render "form" %>

18-auth/snacks_on_a_plane/app/views/snacks/show.html.erb
<h1>snacks show page</h1>

<p> Name: <%= @snack.name %> </p>
<p> Brand: <%= @snack.brand %> </p>
<p> Flavor Profile: <%= @snack.flavor_profile %> </p>

<%= link_to "Edit snack", edit_snack_path(@snack.id) %>
<%= button_to "Delete snack", snack_path(@snack.id), method: :delete %>

<%= link_to "index", snacks_path %>

18-auth/snacks_on_a_plane/app/views/user_snacks/edit.html.erb
<h1>edit review</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p> <%= error %> </p>
    <% end %>
<% end %>

<%= form_for @user_snack do |f| %>
    <%= f.label :review %>
    <%= f.text_field :review %>

    <%= f.label :rating %>
    <%= f.number_field :rating %>

    <%= f.label :snack_id %>
    <%= f.collection_select :snack_id, @snacks, :id, :name %>

    <%= f.submit %>
<% end %>

18-auth/snacks_on_a_plane/app/views/user_snacks/index.html.erb
<h1>All the reviews:</h1>
<ul>
<% @user_snacks.each do |user_snack|%>
    <li><%= link_to user_snack.snack.name, user_snack_path(user_snack.id) %>: <%= user_snack.review %></li>
    <br>
<% end %>
</ul>
<br>
<hr>
☞ <%= link_to "Create a user_snack", new_user_snack_path %>

18-auth/snacks_on_a_plane/app/views/user_snacks/new.html.erb
<h1>new review</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p> <%= error %> </p>
    <% end %>
<% end %>

<%= form_for @user_snack do |f| %>
    <%= f.label :review %>
    <%= f.text_field :review %>

    <%= f.label :rating %>
    <%= f.number_field :rating %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, @users, :id, :name %>

    <%= f.label :snack_id %>
    <%= f.collection_select :snack_id, @snacks, :id, :name %>

    <%= f.submit %>
<% end %>

18-auth/snacks_on_a_plane/app/views/user_snacks/show.html.erb
<h1>Review of <%= @user_snack.snack.name %></h1>
<h4> by <%= @user_snack.user.name %></h4>

<p><%= @user_snack.review %></p>
<p>Rating: <%= @user_snack.rating %></p>

<% if @current_user == @user_snack.user %>
    <%= button_to "Edit", edit_user_snack_path(@user_snack), method: :get %>
    <%= button_to "Delete user_snack", @user_snack, method: :delete %>
<% end %>

18-auth/snacks_on_a_plane/app/views/users/index.html.erb
<h1>users index page</h1>

<% @users.each do |user| %>
    <p><%= link_to user.name, user_path(user.id) %> </p>
<% end %>   

18-auth/snacks_on_a_plane/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :img_url %>
    <%= f.text_field :img_url %>

    <%= f.label :motto %>
    <%= f.text_field :motto %>

    <%= f.submit %>
<% end %>

18-auth/snacks_on_a_plane/app/views/users/show.html.erb
<% if session[:view_count].to_i <= 3 %>

    <h1>user show page</h1>
    <h1>Page Views <%= session[:view_count]%> </h1>

    <h3> <%= @user.name %> </h3>
    <p> <%= @user.motto %> </p>
    <img src="<%= @user.img_url %>" alt="<%= @user.name %>">

    <h5>My Reviews</h5>

    <% @user.user_snacks.each do |user_snack| %>
        <p> Name: <%= user_snack.snack.name %> </p>
        <p> Review: <%= user_snack.review %> </p>
        <p> Rating: <%= user_snack.rating %> </p>
        <hr>
    <% end %>

    <h5>My Snacks</h5>

    <% @user.snacks.each do |snack| %>
        <p> Name: <%= snack.name %> </p>
    <% end %>

<% else %>
    <iframe width="950" height="534" src="https://www.youtube.com/embed/GpOWBIySnzY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


    <%= button_to "I Promise I watched this", reset_path, method: :delete %>
<% end %>